---
include:
  - board: nice_nano_v2
    shield: urchin_left nice_view_adapter  nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: urchin_right nice_view_adapter nice_view_gem
